# Generated by Django 2.1.4 on 2018-12-12 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
